In [1]:

import numpy as np
import scipy.linalg as sla

In [2]:
#Como os dois sistemas são triangulares, e nós já implementamos, em aulas anteriores, 
# funções para resolver esses sistemas, basta, então, construir um implementação integrando 
# todas as "partes" do processo. Considerando que usaremos essas mesmas funções já implementadas, 
# `sist_lin_tri_sup()` e `sist_lin_tri_inf()`, o algoritmo a seguir descreve isso

def sist_lin_tri_inf(A,b):
  n = len(b)
  x = np.empty(n)
  x[0] = b[0]/A[0, 0]
  for i in range(1,n):
    x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
  return x


In [3]:
def sist_lin_tri_sup(A,b):
  n = len(b)
  x = np.empty(n)
  x[-1] = b[-1]/A[-1, -1]
  for i in range(n-2, -1, -1):
   x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
  return x


In [4]:
def decomposicao_doolittle(A):
    n = len(A)
    coeficientes = []
    P = np.identity(n, dtype=np.double)
    L = np.identity(n, dtype=np.double)
    U = A.copy()

    for i in range(n):
        pivot = np.abs(U[i:, i]).argmax() + i
        if i != pivot:
            P[[i, pivot]] = P[[pivot, i]]

    U = P @ A
  
    for i in range(n):
        for j in range(i + 1, n):
            fator = U[j, i] / U[i, i]
            L[j, i] = fator
            U[j] = U[j] - (fator * U[i])

    return P, L, U

In [5]:
def find(P, L, U, b):
  vetor1= sist_lin_tri_inf(L, P @ b)
  vetor2= sist_lin_tri_sup(U, vetor2)

  return vetor1

#### A)

In [6]:
A = np.array([[1,1,1], [4,4,2], [2,1,-1]],  dtype=float)
A

array([[ 1.,  1.,  1.],
       [ 4.,  4.,  2.],
       [ 2.,  1., -1.]])

In [7]:
b = np.array([1,2,0],  dtype=float)
b

array([1., 2., 0.])

In [ ]:
P,L,U = sla.lu(A)
print(f"\n{P};\n -L:\n {L}\n; -U:\n {U}\n\n")
LU, piv = sla.lu_factor(A)

lu, piv = sla.lu_factor(A)
sla.lu_solve((lu, piv), b)

print(f" {sla.lu_solve((lu, piv), b)} \n")


P,L,U = decomposicao_doolittle(A)
print(f"\n-P:\n{P};\n -L:{L};\n -U:\n {U}\n\n")
print(f"{find(P, L, U, b)} \n")


#### B)

In [9]:
A = np.array([[7,-7,1], [-3,3,2], [7,7,-72]],  dtype=float)
A

array([[  7.,  -7.,   1.],
       [ -3.,   3.,   2.],
       [  7.,   7., -72.]])

In [10]:
b = np.array([1,2,7],  dtype=float)
b

array([1., 2., 7.])

In [ ]:
P,L,U = sla.lu(A)
print(f"\n{P};\n -L:\n {L}\n; -U:\n {U}\n\n")
LU, piv = sla.lu_factor(A)

lu, piv = sla.lu_factor(A)
sla.lu_solve((lu, piv), b)

print(f" {sla.lu_solve((lu, piv), b)} \n")


P,L,U = decomposicao_doolittle(A)
print(f" \n-P:\n{P};\n -L:{L};\n -U:\n {U}\n\n")
print(f"{find(P, L, U, b)} \n")


#### C)

In [12]:
A = np.array([[1,2,3,4], [2,2,3,4], [3,3,3,4], [4,4,4,4]],  dtype=float)
A

array([[1., 2., 3., 4.],
       [2., 2., 3., 4.],
       [3., 3., 3., 4.],
       [4., 4., 4., 4.]])

In [13]:
b = np.array([20,22,22,24],  dtype=float)
b

array([20., 22., 22., 24.])

In [ ]:
P,L,U = sla.lu(A)
print(f"\n{P};\n -L:\n {L}\n; -U:\n {U}\n\n")
LU, piv = sla.lu_factor(A)

lu, piv = sla.lu_factor(A)
sla.lu_solve((lu, piv), b)

print(f"{sla.lu_solve((lu, piv), b)} \n")


P,L,U = decomposicao_doolittle(A)
print(f"\n-P:\n{P};\n -L:{L};\n -U:\n {U}\n\n")
print(f"{find(P, L, U, b)} \n")
